### PR TITLE
fix: Added styles back to pagy

### LINKED ISSUE #108: Pagination Styling has Disappeared
Noticed this while working on a feature PR. It looks like the styles themselves went missing. The pagination buttons still have the proper classes assigned to them. I'll keep an eye out and see if I can find where in the commit history that these went missing.

### PR DESCRIPTION
**Pull request by jacobdaddario**
Resolves #108

Did it using the technique described by @excid3 in the issue. Here's a GIF of how it ended up looking:
ezgif-6-b3a54ff20c04

### CODE REVIEW

**Comment by jitingcn** [comment]
I think it would be nicer if we follow the same styles as here: https://ddnexus.github.io/pagy/extras/tailwind

**Comment by jacobdaddario** [comment]
Would we prefer to use the style recommended by @jitingcn or is this good to merge? I have no preference one way or another. I just kept what I originally did because I didn't want to have to redo the work.

**Comment by afomera** [comment]
Could you share what the default suggestion looks like @jacobdaddario?

**Comment by jitingcn** [comment]
V3rcxVGhmD

**Comment by jacobdaddario** [comment]
@jitingcn beat me to it. Do we just want to go with that default look? I can go ahead and modify the PR since I have some time off work starting Wednesday.

**Comment by jitingcn** [comment]
> @jitingcn beat me to it. Do we just want to go with that default look? I can go ahead and modify the PR since I have some time off work starting Wednesday.

I think it doesn't matter if you don't want to change it, your style looks good too.
I'm more familiar with the default style, so I just want to make a suggestion :)

**Comment by afomera** [comment]
I think I'll merge this as-is, as I personally like the styles in the PR. Folks can always generate the views and customize to their preferences as well 👍

**Pull request merged**
