### PR TITLE
Removing .DS_Store file

### PR DESCRIPTION
**Pull request by MikeRogers0**
I was going through the files & spotted a `.DS_Store` file had sneaked into version control :)

So I removed it by running:

```
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch 
```

### CODE REVIEW

**Comment by excid3** [comment]
Thanks! Want to also add this to .gitignore?

**Comment by MikeRogers0** [comment]
@excid3 Done 👍

**Comment by afomera** [comment]
Sniped the PR from @excid3. Thanks @MikeRogers0!

**Comment by excid3** [comment]
no

**Pull request merged**
